server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA — all routes served from index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
